### ISSUE TITLE
Restrict unnecessary Deno permissions

### ISSUE THREAD

**Issue by bartlomieju** [githubocto/flat#12]
Looking at the action script I found: 

https://github.com/githubocto/flat/blob/1c5bd958ca1fd5c1db515c817da6c651abfc09aa/src/main.ts#L44

Deno is run with `-A` flag which enables all permissions; it's probably not a big deal, but it seems that permissions could be restricted a bit to `--allow-read`, `--allow-write`, `--allow-net` and `--allow-env`; ie. disable ability to load native plugins, HR timing and spawning subprocesses.

**Comment by irealva** [comment]
It's a good point and we went back and forth on this, but ultimately we wanted to make the action permissive rather than restrictive.

There are some use cases out there we knew we wouldn't be able to predict. For example, [someone already found a way to create a postprocessing script that incorporates Python](https://github.com/pierrotsmnrd/flat_data_py_example). This was only possible because they spawned a subprocess with the `--allow-run` flag.

**Comment by bartlomieju** [comment]
> There are some use cases out there we knew we wouldn't be able to predict. For example, someone already found a way to create a postprocessing script that incorporates Python. This was only possible because they spawned a subprocess with the --allow-run flag.

Interesting! I could see the use for HR timing as well, though I'd still suggest disabling native plugins for now, as they are quite unstable at the moment. 

Great to see you chose Deno!

**Comment by irealva** [comment]
@idan thoughts?

**Comment by idan** [comment]
@bartlomieju fair! Thank you for reaching out :) As Irene said, Deno is dope, and we love it. We're looking at more ways to use Deno to author actions; the current best practice of "use ncc to build your action before publishing" feels clunky.

@irealva I think we can get more specific in order to disallow plugins. Looking over the [permissions docs](https://deno.land/manual/getting_started/permissions), it's also possible to scope reads/writes to the repo checkout directory, which seems like a sensible guardrail to put in place? And maybe we also disable HR timers.

In practice, anyone who wants these capabilities is not blocked from doing so — either in their own action, or by forking ours and altering it. But guardrails are a good idea!

**Comment by bartlomieju** [comment]
> @bartlomieju fair! Thank you for reaching out :) As Irene said, Deno is dope, and we love it. We're looking at more ways to use Deno to author actions; the current best practice of "use ncc to build your action before publishing" feels clunky.

Sure, happy to provide any assistance necessary, feel free to reach out at our discord.gg/deno

**Comment by irealva** [comment]
@bartlomieju quick clarifying question. If we remove the `--allow-plugin` flag but keep the `--unstable` flag does that mean people would still be able to run plugins?

**Comment by bartlomieju** [comment]
> @bartlomieju quick clarifying question. If we remove the `--allow-plugin` flag but keep the `--unstable` flag does that mean people would still be able to run plugins?

@irealva no, they will still have access to unstable JavaScript APIs (because of `--unstable` flag), but trying to use native plugins will throw a `PermissionDenied` error because of missing `--allow-plugin`.

**Comment by irealva** [comment]
Fantastic, thank you!
