### ISSUE TITLE
RFC: GraphQL Support

### ISSUE THREAD

**Issue by cspray** [githubocto/flat#53]
Hi! Thanks for the awesome functionality provided by Flat Data!

I have come across the need to make a GraphQL query with Flat Data. Specifically, to gather a set of sponsors for a given GitHub organization. I want to then be able to fetch that data in a static website to show a dynamic list of sponsors. I also believe that there could be many other uses for GraphQL queries that are a natural fit for Flat Data.

I am willing to implement a Pull Request to address this functionality. Before I started implementing this change and level of effort I wanted to ensure the maintainers are open to incorporating the feature.

Any feedback is greatly appreciated! Thanks!

**Comment by irealva** [comment]
Hi there, thanks for the questions. This sounds like it could be very helpful and a great addition to Flat.

Would you mind detailing a bit what you're thinking of in terms of the implementation, so we can discuss before you spend the effort in submitting the PR? Is the idea to make the HTTP endpoint more customizable? Or to build an entirely different back-end for GraphQL (we currently have two back ends SQL and HTTP)?

**Comment by cspray** [comment]
Hi, thanks for the response!

At first glance my thought was to make a new back-end. It seems like a different enough use case that I wouldn't want to potentially impact already existing uses of the HTTP back-end. I also believe it might be easier to configure GraphQL concerns with a specific UI, though that is just a hunch. However, I do not have a strong opinion on this and if you believe a shared back-end is better I could rethink my approach.

I believe that the final end-user solution, particularly the VS Code extension, should be very similar to the HTTP process with the addition of a field/textarea for inputting the body of the GraphQL request.

**Comment by irealva** [comment]
Hi there, we decided to implement this ourselves because we wanted to implement something more generalized and less specific to GraphQL.

We landed on exposing an `[axios_config](https://github.com/githubocto/flat#axios_config-optional)` param that let's you pass in the request configuration as a [JSON file](https://github.com/githubocto/flat-demo-graphql/blob/main/query.json). 

Here's a [full demo making a GraphQL query](https://github.com/githubocto/flat-demo-graphql) to the GitHub API. You'll notice the demo also shows you to use an [authorization key](https://github.com/githubocto/flat-demo-graphql/blob/main/.github/workflows/flat.yaml#L29) as part of the request.

**Comment by cspray** [comment]
This is awesome! Thanks so much for implementing this functionality.
